'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

export type Language = 'tr' | 'en' | 'de'

// Simple direct translations without i18n
const translations = {
  en: {
    common: {
      title: "SourceCheck AI", // Brand name - never translate
      subtitle: "AI-Powered Content Verification",
      description: "Detect whether texts and images are generated by AI",
      heroTitle: "Detect AI-Generated Content",
      heroDescription: "Analyze whether text, image and video content is generated by AI. Track sources and verify originality.",
      startFree: "Start Free",
      watchDemo: "Watch Demo",
      analyze: "Analyze",
      analyzing: "Analyzing...",
      results: "Results",
      confidence: "Confidence",
      aiGenerated: "AI Generated",
      humanGenerated: "Human Generated",
      uncertain: "Uncertain",
      sources: "Sources",
      model: "Model",
      timestamp: "Timestamp",
      language: "Language",
      settings: "Settings",
      profile: "Profile",
      logout: "Logout",
      login: "Login",
      signup: "Sign Up",
      dashboard: "Dashboard",
      history: "History",
      upload: "Upload",
      paste: "Paste",
      clear: "Clear",
      save: "Save",
      cancel: "Cancel",
      error: "Error",
      success: "Success",
      warning: "Warning",
      info: "Info",
      user: "User",
      
      // Features section
      whySourceCheck: "Why SourceCheck AI?",
      advancedAnalysis: "Advanced Analysis",
      advancedAnalysisDesc: "Content analysis with 99.5% accuracy using the latest AI technologies",
      securePrivate: "Secure and Private", 
      securePrivateDesc: "Your data is encrypted and never shared with third parties",
      detailedReporting: "Detailed Reporting",
      detailedReportingDesc: "Comprehensive reports with source tracking and explanatory analysis",
      
      // Pricing section
      pricingPlans: "Pricing Plans",
      free: "Free",
      pro: "Pro", 
      enterprise: "Enterprise",
      popular: "Popular",
      perMonth: "/month",
      getStarted: "Get Started",
      upgradeToProo: "Upgrade to Pro",
      contactUs: "Contact Us",
      
      // Pricing features
      dailyAnalyses10: "10 analyses per day",
      dailyAnalyses500: "500 analyses per day", 
      unlimitedAnalyses: "Unlimited analyses",
      basicReporting: "Basic reporting",
      advancedReporting: "Advanced reporting",
      customReporting: "Custom reporting",
      emailSupport: "Email support",
      prioritySupport: "Priority support",
      support247: "24/7 support",
      apiAccess: "API access",
      customIntegrations: "Custom integrations",
      
      // Footer
      productTitle: "Product",
      features: "Features",
      pricing: "Pricing", 
      api: "API",
      supportTitle: "Support",
      helpCenter: "Help Center",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      contact: "Contact",
      footerDescription: "Your reliable solution for AI content detection and source tracking.",
      copyright: "© 2024 SourceCheck AI. All rights reserved."
    },
    analysis: {
      textAnalysis: "Text Analysis",
      imageAnalysis: "Image Analysis",
      videoAnalysis: "Video Analysis",
      enterText: "Enter text to analyze here...",
      pasteContent: "Paste your content here",
      dragAndDrop: "Drag and drop your file here",
      selectFile: "Select File",
      upload: "Upload",
      analyzing: "Analyzing...",
      result: "Result",
      confidence: "Confidence Level",
      sources: "Sources Found",
      explanation: "Analysis Explanation",
      aiGenerated: "AI Generated",
      humanGenerated: "Human Generated",
      uncertain: "Uncertain"
    },
    settings: {
      languageSettings: "Language Settings",
      selectLanguage: "Select Language",
      turkish: "Türkçe",
      english: "English",
      german: "Deutsch",
      apiSettings: "API Settings",
      mistralApiKey: "Mistral API Key",
      modelSelection: "Model Selection",
      saveSettings: "Save Settings",
      resetSettings: "Reset Settings",
      settingsSaved: "Settings saved",
      settingsError: "Failed to save settings",
      settings: "Settings",
      language: "Language",
      profile: "Profile",
      defaultModel: "Default Model",
      enterApiKey: "Enter your Mistral API key",
      testConnection: "Test Connection",
      connectionSuccessful: "API connection successful",
      connectionFailed: "API connection failed",
      profileSettings: "Profile Settings",
      displayName: "Display Name",
      emailAddress: "Email Address",
      accountType: "Account Type",
      memberSince: "Member Since",
      updateProfile: "Update Profile",
      profileUpdated: "Profile updated successfully"
    },
    profile: {
      userProfile: "User Profile",
      personalInfo: "Personal Information",
      preferences: "Preferences",
      accountSettings: "Account Settings",
      changePassword: "Change Password",
      deleteAccount: "Delete Account",
      exportData: "Export Data"
    },
    navigation: {
      home: "Home",
      textAnalysis: "Text Analysis",
      imageAnalysis: "Image Analysis",
      history: "History",
      settings: "Settings",
      profile: "Profile",
      about: "About",
      contact: "Contact",
      help: "Help",
      dashboard: "Dashboard",
      login: "Login",
      signup: "Sign Up",
      logout: "Logout",
      billing: "Billing",
      menu: "Menu"
    },
    dashboard: {
      welcome: "Welcome",
      analysisResults: "Analysis Results",
      enterTextPlaceholder: "Enter text to analyze here...",
      dragDropImage: "Drag image here or click to upload",
      supportedFormats: "Supported formats: JPG, PNG, WEBP (Max. 10MB)",
      analyzeButton: "Analyze",
      clearButton: "Clear",
      analyzing: "Analyzing...",
      analysisComplete: "Analysis complete",
      errorOccurred: "Error occurred",
      pleaseEnterText: "Please enter text to analyze.",
      pleaseUploadImage: "Please upload an image to analyze.",
      unsupportedFormat: "Unsupported file format. Please upload JPG, PNG or WEBP file.",
      fileTooLarge: "File size too large. Maximum file size is 10MB.",
      confidenceScore: "Confidence Score",
      detectionResult: "Detection Result",
      analysisSource: "Analysis Source",
      provideFeedback: "Provide feedback",
      feedbackCorrect: "Result is correct",
      feedbackIncorrect: "Result is incorrect",
      feedbackThanks: "Thank you for your feedback!",
      recentAnalyses: "Recent Analyses",
      noHistory: "You don't have any analysis history yet.",
      overview: "Overview",
      textAnalysis: "Text Analysis",
      imageAnalysis: "Image Analysis",
      videoAnalysis: "Video Analysis",
      enterTextHere: "Enter text to analyze here...",
      analyzeText: "Analyze Text",
      uploadImage: "Upload Image",
      analyzeImage: "Analyze Image",
      wasThisCorrect: "Was this analysis correct?",
      yes: "Yes",
      no: "No",
      aiGenerated: "AI Generated",
      humanGenerated: "Human Generated",
      uncertain: "Uncertain",
      submitFeedback: "Submit Feedback",
      apiKeyRequired: "API key required. Please set your Mistral API key in settings.",
      highConfidenceAI: "High confidence - AI generated",
      mediumConfidenceAI: "Medium confidence - likely AI generated",
      lowConfidenceAI: "Low confidence - possibly AI generated",
      highConfidenceHuman: "High confidence - Human generated",
      mediumConfidenceHuman: "Medium confidence - likely Human generated",
      lowConfidenceHuman: "Low confidence - possibly Human generated",
      uncertainResult: "Uncertain - requires further analysis"
    },
    errors: {
      networkError: "Network connection error",
      serverError: "Server error",
      fileUploadError: "File upload error",
      analysisError: "Analysis error",
      settingsError: "Settings error",
      loginError: "Login error",
      signupError: "Sign up error",
      genericError: "An error occurred"
    },
    login: {
      signInToAccount: "Sign in to your account",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
      demoAccess: "Demo Access",
      username: "Username / Email",
      password: "Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot your password?",
      signIn: "Sign In",
      signingIn: "Signing in...",
      or: "Or",
      invalidCredentials: "Invalid username or password. For demo: admin/admin",
      demoUsername: "For demo: admin",
      demoPassword: "For demo: admin",
      googleSignIn: "Sign in with Google"
    },
    signup: {
      createAccount: "Create your account",
      alreadyHaveAccount: "Already have an account?",
      signIn: "Sign in",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      creating: "Creating account...",
      agreeToTerms: "I agree to the Terms of Service and Privacy Policy",
      termsOfService: "Terms of Service",
      privacyPolicy: "Privacy Policy"
    },
    features: {
      whySourceCheck: "Why SourceCheck AI?",
      advancedAnalysis: "Advanced Analysis",
      advancedAnalysisDesc: "Content analysis with 99.5% accuracy using the latest AI technologies",
      securePrivate: "Secure and Private",
      securePrivateDesc: "Your data is encrypted and never shared with third parties",
      detailedReporting: "Detailed Reporting",
      detailedReportingDesc: "Comprehensive reports with source tracking and explanatory analysis"
    },
    pricing: {
      pricingPlans: "Pricing Plans",
      free: "Free",
      freePrice: "$0/month",
      freeFeatures: ["10 analyses per day", "Basic reporting", "Email support"],
      pro: "Pro",
      proPrice: "$99/month",
      proFeatures: ["500 analyses per day", "Advanced reporting", "API access", "Priority support"],
      enterprise: "Enterprise",
      enterprisePrice: "$499/month",
      enterpriseFeatures: ["Unlimited analyses", "Custom reporting", "Custom integrations", "24/7 support"],
      popular: "Popular",
      getStarted: "Get Started",
      upgradeToPro: "Upgrade to Pro",
      contactUs: "Contact Us"
    },
    footer: {
      description: "Your reliable solution for AI content detection and source tracking.",
      product: "Product",
      features: "Features",
      pricing: "Pricing",
      api: "API",
      support: "Support",
      helpCenter: "Help Center",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      contact: "Contact",
      allRightsReserved: "All rights reserved"
    }
  },
  tr: {
    common: {
      title: "SourceCheck AI", // Brand name - never translate
      subtitle: "AI Destekli İçerik Doğrulama",
      description: "Metinlerin ve görsellerin AI tarafından üretilip üretilmediğini tespit edin",
      heroTitle: "AI Üretimi İçerik Tespiti",
      heroDescription: "Metin, görsel ve video içeriklerin AI tarafından üretilip üretilmediğini analiz edin. Kaynak takibi yapın ve özgünlüğü doğrulayın.",
      startFree: "Ücretsiz Başla",
      watchDemo: "Demo İzle",
      analyze: "Analiz Et",
      analyzing: "Analiz Ediliyor...",
      results: "Sonuçlar",
      confidence: "Güven",
      save: "Kaydet",
      cancel: "İptal",
      confirm: "Onayla",
      delete: "Sil",
      edit: "Düzenle",
      loading: "Yükleniyor...",
      error: "Hata",
      success: "Başarılı",
      warning: "Uyarı",
      info: "Bilgi",
    },
    analysis: {
      textAnalysis: "Metin Analizi",
      imageAnalysis: "Görsel Analizi",
      videoAnalysis: "Video Analizi",
      enterText: "Analiz edilecek metni buraya girin...",
      pasteContent: "İçeriğinizi buraya yapıştırın",
      dragAndDrop: "Dosyanızı buraya sürükleyip bırakın",
      selectFile: "Dosya Seç",
      upload: "Yükle", 
      analyzing: "Analiz Ediliyor...",
      result: "Sonuç",
      confidence: "Güven Seviyesi",
      sources: "Bulunan Kaynaklar",
      explanation: "Analiz Açıklaması",
      aiGenerated: "AI Üretimi",
      humanGenerated: "İnsan Üretimi",
      uncertain: "Belirsiz",
      aiDetection: "AI Tespiti",
      originalAuthor: "Orijinal Yazar",
      similarity: "Benzerlik",
      model: "Model",
      timestamp: "Zaman Damgası",
      processing: "İşleniyor",
      completed: "Tamamlandı",
      failed: "Başarısız"
    },
    settings: {
      languageSettings: "Dil Ayarları",
      selectLanguage: "Dil Seçin",
      turkish: "Türkçe",
      english: "English",
      german: "Deutsch",
      apiSettings: "API Ayarları",
      mistralApiKey: "Mistral API Anahtarı",
      modelSelection: "Model Seçimi",
      saveSettings: "Ayarları Kaydet",
      resetSettings: "Ayarları Sıfırla",
      settingsSaved: "Ayarlar kaydedildi",
      settingsError: "Ayarlar kaydedilemedi",
      settings: "Ayarlar",
      language: "Dil",
      profile: "Profil",
      defaultModel: "Varsayılan Model",
      enterApiKey: "Mistral API anahtarınızı girin",
      testConnection: "Bağlantıyı Test Et",
      connectionSuccessful: "API bağlantısı başarılı",
      connectionFailed: "API bağlantısı başarısız",
      profileSettings: "Profil Ayarları",
      displayName: "Görünen Ad",
      emailAddress: "E-posta Adresi",
      accountType: "Hesap Türü",
      memberSince: "Üyelik Tarihi",
      updateProfile: "Profili Güncelle",
      profileUpdated: "Profil başarıyla güncellendi"
    },
    profile: {
      userProfile: "Kullanıcı Profili",
      personalInfo: "Kişisel Bilgiler",
      preferences: "Tercihler",
      accountSettings: "Hesap Ayarları",
      changePassword: "Şifre Değiştir",
      deleteAccount: "Hesabı Sil",
      exportData: "Verileri Dışa Aktar"
    },
    navigation: {
      home: "Ana Sayfa",
      textAnalysis: "Metin Analizi",
      imageAnalysis: "Görsel Analizi",
      history: "Geçmiş",
      settings: "Ayarlar",
      profile: "Profil",
      about: "Hakkında", 
      contact: "İletişim",
      dashboard: "Gösterge Paneli",
      login: "Giriş",
      signup: "Üye Ol",
      logout: "Çıkış",
      billing: "Faturalama",
      menu: "Menü"
    },
    dashboard: {
      welcome: "Hoş Geldiniz",
      overview: "Genel Bakış",
      textAnalysis: "Metin Analizi",
      imageAnalysis: "Görsel Analizi",
      videoAnalysis: "Video Analizi",
      enterTextHere: "Analiz edilecek metni buraya girin...",
      analyzeText: "Metni Analiz Et",
      uploadImage: "Görsel Yükle",
      dragDropImage: "Bir görseli buraya sürükleyip bırakın veya seçmek için tıklayın",
      supportedFormats: "Desteklenen formatlar: JPG, PNG, WEBP (max 10MB)",
      analyzeImage: "Görseli Analiz Et",
      pleaseEnterText: "Lütfen analiz edilecek bir metin girin",
      pleaseUploadImage: "Lütfen analiz edilecek bir görsel yükleyin",
      unsupportedFormat: "Desteklenmeyen dosya formatı. Lütfen JPG, PNG veya WEBP kullanın",
      fileTooLarge: "Dosya çok büyük. Maksimum boyut 10MB",
      wasThisCorrect: "Bu analiz doğru muydu?",
      yes: "Evet",
      no: "Hayır",
      provideFeedback: "Lütfen doğru sınıflandırmayı belirtin:",
      aiGenerated: "AI Üretimi",
      humanGenerated: "İnsan Üretimi",
      uncertain: "Belirsiz",
      submitFeedback: "Geri Bildirim Gönder",
      thankYouFeedback: "Geri bildiriminiz için teşekkürler!",
      apiKeyRequired: "API anahtarı gerekli. Lütfen ayarlarda Mistral API anahtarınızı belirleyin.",
      highConfidenceAI: "Yüksek güven - AI üretimi",
      mediumConfidenceAI: "Orta güven - muhtemelen AI üretimi",
      lowConfidenceAI: "Düşük güven - olasılıkla AI üretimi",
      highConfidenceHuman: "Yüksek güven - İnsan üretimi",
      mediumConfidenceHuman: "Orta güven - muhtemelen İnsan üretimi",
      lowConfidenceHuman: "Düşük güven - olasılıkla İnsan üretimi",
      uncertainResult: "Belirsiz - daha fazla analiz gerekiyor"
    },
    errors: {
      networkError: "Ağ bağlantısı hatası",
      serverError: "Sunucu hatası",
      fileUploadError: "Dosya yükleme hatası",
      analysisError: "Analiz hatası",
      settingsError: "Ayarlar hatası",
      loginError: "Giriş hatası",
      signupError: "Kayıt hatası",
      genericError: "Bir hata oluştu"
    },
    login: {
      signInToAccount: "Hesabınıza giriş yapın",
      noAccount: "Henüz hesabınız yok mu?",
      signUp: "Üye olun",
      demoAccess: "Demo Erişimi",
      username: "Kullanıcı Adı / E-posta",
      password: "Şifre",
      rememberMe: "Beni hatırla",
      forgotPassword: "Şifremi unuttum",
      signIn: "Giriş Yap",
      signingIn: "Giriş yapılıyor...",
      or: "Veya",
      invalidCredentials: "Geçersiz kullanıcı adı veya şifre. Demo için: admin/admin",
      demoUsername: "Demo için: admin",
      demoPassword: "Demo için: admin",
      googleSignIn: "Google ile giriş yap"
    },
    signup: {
      createAccount: "Hesap oluşturun",
      alreadyHaveAccount: "Zaten hesabınız var mı?",
      signIn: "Giriş yapın",
      firstName: "Ad",
      lastName: "Soyad",
      email: "E-posta",
      password: "Şifre",
      confirmPassword: "Şifre Tekrarı",
      creating: "Hesap oluşturuluyor...",
      agreeToTerms: "Hizmet Şartları ve Gizlilik Politikası'nı kabul ediyorum",
      termsOfService: "Hizmet Şartları",
      privacyPolicy: "Gizlilik Politikası"
    },
    features: {
      whySourceCheck: "Neden SourceCheck AI?",
      advancedAnalysis: "Gelişmiş Analiz",
      advancedAnalysisDesc: "En son AI teknolojileri kullanarak %99.5 doğrulukla içerik analizi",
      securePrivate: "Güvenli ve Özel",
      securePrivateDesc: "Verileriniz şifrelenir ve üçüncü taraflarla asla paylaşılmaz",
      detailedReporting: "Detaylı Raporlama",
      detailedReportingDesc: "Kaynak takibi ve açıklayıcı analiz ile kapsamlı raporlar"
    },
    pricing: {
      pricingPlans: "Fiyatlandırma Planları",
      free: "Ücretsiz",
      freePrice: "$0/ay",
      freeFeatures: ["Günde 10 analiz", "Temel raporlama", "E-posta desteği"],
      pro: "Pro",
      proPrice: "$99/ay",
      proFeatures: ["Günde 500 analiz", "Gelişmiş raporlama", "API erişimi", "Öncelikli destek"],
      enterprise: "Kurumsal",
      enterprisePrice: "$499/ay",
      enterpriseFeatures: ["Sınırsız analiz", "Özel raporlama", "Özel entegrasyonlar", "7/24 destek"],
      popular: "Popüler",
      getStarted: "Başla",
      upgradeToPro: "Pro'ya Yükselt",
      contactUs: "Bize Ulaşın"
    },
    footer: {
      description: "AI içerik tespiti ve kaynak takibi için güvenilir çözümünüz.",
      product: "Ürün",
      features: "Özellikler",
      pricing: "Fiyatlandırma",
      api: "API",
      support: "Destek",
      helpCenter: "Yardım Merkezi",
      privacyPolicy: "Gizlilik Politikası",
      termsOfService: "Hizmet Şartları",
      contact: "İletişim",
      allRightsReserved: "Tüm hakları saklıdır"
    }
  },
  de: {
    common: {
      title: "SourceCheck AI", // Brand name - never translate
      subtitle: "KI-gestützte Inhaltsverifizierung",
      description: "Erkennen Sie, ob Texte und Bilder von KI generiert wurden",
      heroTitle: "KI-generierte Inhalte erkennen",
      heroDescription: "Analysieren Sie, ob Text-, Bild- und Videoinhalte von KI generiert wurden. Verfolgen Sie Quellen und verifizieren Sie die Originalität.",
      startFree: "Kostenlos starten",
      watchDemo: "Demo ansehen",
      analyze: "Analysieren",
      analyzing: "Analysiere...",
      results: "Ergebnisse",
      confidence: "Vertrauen",
      aiGenerated: "KI-generiert",
      humanGenerated: "Von Menschen erstellt",
      uncertain: "Ungewiss",
      sources: "Quellen",
      model: "Modell",
      timestamp: "Zeitstempel",
      language: "Sprache",
      settings: "Einstellungen",
      profile: "Profil",
      logout: "Abmelden",
      login: "Anmelden",
      signup: "Registrieren",
      dashboard: "Dashboard",
      history: "Verlauf",
      upload: "Hochladen",
      paste: "Einfügen",
      clear: "Löschen",
      save: "Speichern",
      cancel: "Abbrechen",
      error: "Fehler",
      success: "Erfolgreich",
      warning: "Warnung",
      info: "Info",
    },
    analysis: {
      textAnalysis: "Textanalyse",
      imageAnalysis: "Bildanalyse", 
      videoAnalysis: "Videoanalyse",
      enterText: "Geben Sie hier den zu analysierenden Text ein...",
      pasteContent: "Fügen Sie Ihren Inhalt hier ein",
      dragAndDrop: "Ziehen Sie Ihre Datei hierher",
      selectFile: "Datei auswählen",
      upload: "Hochladen",
      analyzing: "Analysiere...",
      result: "Ergebnis",
      confidence: "Vertrauensstufe",
      sources: "Gefundene Quellen",
      explanation: "Analyse-Erklärung",
      aiGenerated: "KI-generiert",
      humanGenerated: "Von Menschen erstellt",
      uncertain: "Ungewiss",
      aiDetection: "KI-Erkennung",
      originalAuthor: "Originalautor",
      similarity: "Ähnlichkeit",
      model: "Modell",
      timestamp: "Zeitstempel",
      processing: "Verarbeitung",
      completed: "Abgeschlossen",
      failed: "Fehlgeschlagen"
    },
    settings: {
      languageSettings: "Spracheinstellungen",
      selectLanguage: "Sprache wählen",
      turkish: "Türkçe",
      english: "English",
      german: "Deutsch",
      apiSettings: "API-Einstellungen",
      mistralApiKey: "Mistral API-Schlüssel",
      modelSelection: "Modellauswahl",
      saveSettings: "Einstellungen speichern",
      resetSettings: "Einstellungen zurücksetzen",
      settingsSaved: "Einstellungen gespeichert",
      settingsError: "Einstellungen konnten nicht gespeichert werden",
      settings: "Einstellungen",
      language: "Sprache",
      profile: "Profil",
      defaultModel: "Standardmodell",
      enterApiKey: "Geben Sie Ihren Mistral API-Schlüssel ein",
      testConnection: "Verbindung testen",
      connectionSuccessful: "API-Verbindung erfolgreich",
      connectionFailed: "API-Verbindung fehlgeschlagen",
      profileSettings: "Profil-Einstellungen",
      displayName: "Anzeigename",
      emailAddress: "E-Mail-Adresse",
      accountType: "Kontotyp",
      memberSince: "Mitglied seit",
      updateProfile: "Profil aktualisieren",
      profileUpdated: "Profil erfolgreich aktualisiert"
    },
    profile: {
      userProfile: "Benutzerprofil",
      personalInfo: "Persönliche Informationen",
      preferences: "Einstellungen",
      accountSettings: "Kontoeinstellungen",
      changePassword: "Passwort ändern",
      deleteAccount: "Konto löschen",
      exportData: "Daten exportieren"
    },
    navigation: {
      home: "Startseite",
      textAnalysis: "Textanalyse",
      imageAnalysis: "Bildanalyse",
      history: "Verlauf",
      settings: "Einstellungen",
      profile: "Profil",
      about: "Über",
      contact: "Kontakt",
      help: "Hilfe",
      dashboard: "Dashboard",
      login: "Anmelden",
      signup: "Registrieren",
      logout: "Abmelden",
      billing: "Abrechnung",
      menu: "Menü"
    },
    dashboard: {
      welcome: "Willkommen",
      analysisResults: "Analyseergebnisse",
      enterTextPlaceholder: "Text zur Analyse hier eingeben...",
      dragDropImage: "Bild hierhin ziehen oder zum Hochladen klicken",
      supportedFormats: "Unterstützte Formate: JPG, PNG, WEBP (Max. 10MB)",
      analyzeButton: "Analysieren",
      clearButton: "Löschen",
      analyzing: "Analysiert...",
      analysisComplete: "Analyse abgeschlossen",
      errorOccurred: "Fehler aufgetreten",
      pleaseEnterText: "Bitte geben Sie Text zur Analyse ein.",
      pleaseUploadImage: "Bitte laden Sie ein Bild zur Analyse hoch.",
      unsupportedFormat: "Nicht unterstütztes Dateiformat. Bitte JPG, PNG oder WEBP hochladen.",
      fileTooLarge: "Dateigröße zu groß. Maximale Dateigröße ist 10MB.",
      confidenceScore: "Vertrauensscore",
      detectionResult: "Erkennungsergebnis",
      analysisSource: "Analysequelle",
      provideFeedback: "Feedback geben",
      feedbackCorrect: "Ergebnis ist korrekt",
      feedbackIncorrect: "Ergebnis ist falsch",
      feedbackThanks: "Vielen Dank für Ihr Feedback!",
      recentAnalyses: "Letzte Analysen",
      noHistory: "Sie haben noch keine Analysehistorie."
    },
    errors: {
      networkError: "Netzwerkverbindungsfehler",
      serverError: "Serverfehler",
      fileUploadError: "Datei-Upload-Fehler",
      analysisError: "Analysefehler",
      settingsError: "Einstellungsfehler",
      loginError: "Anmeldefehler",
      signupError: "Registrierungsfehler",
      genericError: "Ein Fehler ist aufgetreten"
    },
    login: {
      signInToAccount: "Bei Ihrem Konto anmelden",
      noAccount: "Haben Sie noch kein Konto?",
      signUp: "Registrieren",
      demoAccess: "Demo-Zugang",
      username: "Benutzername / E-Mail",
      password: "Passwort",
      rememberMe: "Angemeldet bleiben",
      forgotPassword: "Passwort vergessen?",
      signIn: "Anmelden",
      signingIn: "Anmelden...",
      or: "Oder",
      invalidCredentials: "Ungültiger Benutzername oder Passwort. Für Demo: admin/admin",
      demoUsername: "Für Demo: admin",
      demoPassword: "Für Demo: admin",
      googleSignIn: "Mit Google anmelden"
    },
    signup: {
      createAccount: "Konto erstellen",
      alreadyHaveAccount: "Haben Sie bereits ein Konto?",
      signIn: "Anmelden",
      firstName: "Vorname",
      lastName: "Nachname", 
      email: "E-Mail",
      password: "Passwort",
      confirmPassword: "Passwort bestätigen",
      creating: "Konto wird erstellt...",
      agreeToTerms: "Ich stimme den Nutzungsbedingungen und der Datenschutzerklärung zu",
      termsOfService: "Nutzungsbedingungen",
      privacyPolicy: "Datenschutzerklärung"
    },
    features: {
      whySourceCheck: "Warum SourceCheck AI?",
      advancedAnalysis: "Erweiterte Analyse",
      advancedAnalysisDesc: "Inhaltsanalyse mit 99,5% Genauigkeit unter Verwendung der neuesten KI-Technologien",
      securePrivate: "Sicher und Privat",
      securePrivateDesc: "Ihre Daten werden verschlüsselt und niemals an Dritte weitergegeben",
      detailedReporting: "Detaillierte Berichterstattung",
      detailedReportingDesc: "Umfassende Berichte mit Quellenverfolgung und erklärender Analyse"
    },
    pricing: {
      pricingPlans: "Preispläne",
      free: "Kostenlos",
      freePrice: "0€/Monat",
      freeFeatures: ["10 Analysen pro Tag", "Basis-Berichterstattung", "E-Mail-Support"],
      pro: "Pro",
      proPrice: "99€/Monat",
      proFeatures: ["500 Analysen pro Tag", "Erweiterte Berichterstattung", "API-Zugang", "Prioritäts-Support"],
      enterprise: "Enterprise",
      enterprisePrice: "499€/Monat",
      enterpriseFeatures: ["Unbegrenzte Analysen", "Benutzerdefinierte Berichterstattung", "Benutzerdefinierte Integrationen", "24/7 Support"],
      popular: "Beliebt",
      getStarted: "Loslegen",
      upgradeToPro: "Auf Pro upgraden",
      contactUs: "Kontaktieren Sie uns"
    },
    footer: {
      description: "Ihre zuverlässige Lösung für KI-Inhaltserkennung und Quellenverfolgung.",
      product: "Produkt",
      features: "Funktionen",
      pricing: "Preise",
      api: "API",
      support: "Support",
      helpCenter: "Hilfezentrum",
      privacyPolicy: "Datenschutzerklärung",
      termsOfService: "Nutzungsbedingungen",
      contact: "Kontakt",
      allRightsReserved: "Alle Rechte vorbehalten"
    }
  }
}

interface LanguageContextType {
  currentLanguage: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  tLogin: (key: string) => string
  tSignup: (key: string) => string
  tDashboard: (key: string) => string
  tSettings: (key: string) => string
  tAnalysis: (key: string) => string
  tNavigation: (key: string) => string
  tFeatures: (key: string) => string
  tPricing: (key: string) => string
  tFooter: (key: string) => string
  tProfile: (key: string) => string
  availableLanguages: { code: Language; name: string; nativeName: string }[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const availableLanguages = [
  { code: 'en' as Language, name: 'English', nativeName: 'English' },
  { code: 'tr' as Language, name: 'Turkish', nativeName: 'Türkçe' },
  { code: 'de' as Language, name: 'German', nativeName: 'Deutsch' }
]

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en') // Default to English

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language)
      document.documentElement.lang = language
    }
  }

  // Helper functions for different translation categories
  const t = (key: string): string => {
    try {
      const commonTranslations = translations[currentLanguage]?.common as any
      return commonTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tLogin = (key: string): string => {
    try {
      const loginTranslations = translations[currentLanguage]?.login as any
      return loginTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tSignup = (key: string): string => {
    try {
      const signupTranslations = translations[currentLanguage]?.signup as any
      return signupTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tDashboard = (key: string): string => {
    try {
      const dashboardTranslations = translations[currentLanguage]?.dashboard as any
      return dashboardTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tSettings = (key: string): string => {
    try {
      const settingsTranslations = translations[currentLanguage]?.settings as any
      return settingsTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tAnalysis = (key: string): string => {
    try {
      const analysisTranslations = translations[currentLanguage]?.analysis as any
      return analysisTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tNavigation = (key: string): string => {
    try {
      const navigationTranslations = translations[currentLanguage]?.navigation as any
      return navigationTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tFeatures = (key: string): string => {
    try {
      const featuresTranslations = translations[currentLanguage]?.features as any
      return featuresTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tPricing = (key: string): string => {
    try {
      const pricingTranslations = translations[currentLanguage]?.pricing as any
      return pricingTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tFooter = (key: string): string => {
    try {
      const footerTranslations = translations[currentLanguage]?.footer as any
      return footerTranslations?.[key] || key
    } catch {
      return key
    }
  }

  const tProfile = (key: string): string => {
    try {
      const profileTranslations = translations[currentLanguage]?.profile as any
      return profileTranslations?.[key] || key
    } catch {
      return key
    }
  }

  // Load saved language on mount
  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language
      if (savedLanguage && availableLanguages.some(lang => lang.code === savedLanguage)) {
        setCurrentLanguage(savedLanguage)
        document.documentElement.lang = savedLanguage
      }
    }
  }, [])

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      setLanguage,
      t,
      tLogin,
      tSignup,
      tDashboard,
      tSettings,
      tAnalysis,
      tNavigation,
      tFeatures,
      tPricing,
      tFooter,
      tProfile,
      availableLanguages
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useTranslations() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useTranslations must be used within a LanguageProvider')
  }
  return context
}

// Additional hook for backward compatibility
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 